practice_laravel/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\StudentController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/home', function () {
    return view('welcome');
});

Route::resource('students', StudentController::class)->middleware('auth');

// Route::get('/login', AdminController::class, 'index')->name('login.index');
// Route::get('/logout', AdminController::class, 'logout')->name('login.logout');
// Route::post('/login', AdminController::class, 'process')->name('login.process');

Route::get('/login', [AdminController::class, 'index'])->name('login');
Route::get('/logout', [AdminController::class, 'logout']);
Route::post('/login', [AdminController::class, 'process'])->name('login.process');

practice_laravel/app/Models/Admin.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Admin extends Model
{
    use HasFactory;
    protected $table = 'admins';
    protected $filable = ['username', 'password'];
}

practice_laravel/app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    use HasFactory;
    protected $guarded = [];

    // protected $fillable = [
    //     '',
    //     'email',
    //     'password',
    //     'email_verified_at',
    // ];
}

practice_laravel/app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

practice_laravel/app/Http/Controllers/AdminController.php
<?php

namespace App\Http\Controllers;

use App\Models\Admin;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AdminController extends Controller
{
    public function index()
    {
        return view('login.login');
    }

    public function process(Request $request)
    {
        $credentials = $request->validate([
            'username' => 'required',
            'password' => 'required',
        ]);


        if (Auth::attempt($credentials)) {
            $request->session()->regenerate();

            return redirect()->intended('/students')->with('loginSuccess', 'Login Berhasil');
        }
        return back()->with('loginError', 'Login Gagal');
    }

    public function logout()
    {
        session()->forget('username');
        return redirect('login')->with('pesan', 'Logoutberhasil');
    }
}

practice_laravel/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

practice_laravel/app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Student;

use Illuminate\Http\Request;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $students = Student::latest()->paginate(5);

        return view('students.index', compact('students'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('students.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',

        ]);

        Student::create($request->all());

        return redirect()->route('students.index')
            ->with('success', 'Student created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('students.show', [
            'student' => Student::findOrFail($id)

        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('students.edit', [
            'student' => Student::findOrFail($id)


        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Student $student)
    {
        $request->validate([
            'name' => 'required',

        ]);

        $student->update($request->all());

        return redirect()->route('students.index')
            ->with('success', 'Student updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Student $student)
    {
        $student->delete();

        return redirect()->route('students.index')
            ->with('success', 'Student deleted successfully');
    }
}

practice_laravel/resources/views/login/login.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body>
    <div class="container mt-3">
        <div class="row">
            <div class="col-12">
                <div class="py-4 d-flex justify-content-end align-items-center">
                    <h2 class="mr-auto">Login</h2>
                </div>
                @if(session()->has('pesan'))
                <div class="alert alert-success">{{session()->get('pesan')}}
                </div>
                @endif
                <form action="{{ route('login.process') }}" method="POST">
                    @csrf
                    <div class="form-group">
                        <label for="nim">Username</label>
                        <input type="text" class="form-control @error('username') is-invalid @enderror" id="username"
                            name="username" value="{{ old('username') }}">
                        @error('username')
                        <div class="text-danger">{{$message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" class="form-control @error('password') is-invalid @enderror"
                            id="password" name="password" value="{{ old('password') }}">
                        @error('password')
                        <div class="text-danger">{{ $message}}</div>
                        @enderror
                    </div>
                    <button type="submit" class="btn btn-primary mb-2">Daftar</button>
                </form>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
    </script>

</body>

</html>

practice_laravel/resources/views/students/create.blade.php
@extends('students.layout')

@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div>
            <h2>Add New Student</h2>
        </div>
        <div>
            <a class="btn btn-primary" href="{{ route('students.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

<form action="{{ route('students.store') }}" method="POST">
    @csrf

    <div class="row">
        <div class="form-group">
            <label for="nim">NIM</label>
            <input type="text" class="form-control @error('nim') is-invalid @enderror" id="nim" name="nim"
                value="{{old('nim')}}">

            @error('nim')
            <div class="text-danger">
                {{$message}}
            </div>
            @enderror
        </div>
        <div class="form-group">
            <label for="name">NamaLengkap</label>
            <input type="text" class="form-control @error('name')is-invalid @enderror" id="name" name="name"
                value="{{old('nama')}}">
            @error('nama')
            <div class="text-danger">
                {{$message}}
            </div>
            @enderror
        </div>
        <div class="form-group"><label>Jenis Kelamin</label>
            <div>
                <div class="form-checkform-check-inline">
                    <input class="form-check-input" type="radio" name="gender" id="laki_laki" value="L"
                        {{old('gender')=='L' ?'checked':''}}>
                    <label class="form-check-label" for="laki_laki">Laki-laki</label>
                </div>
                <div class="form-checkform-check-inline">
                    <input class="form-check-input" type="radio" name="gender" id="perempuan" value="P"
                        {{old('gender')=='P' ?'checked':''}}>
                    <label class="form-check-label" for="perempuan">Perempuan</label>
                </div>
                @error('gender')
                <div class="text-danger">
                    {{$message}}
                </div>@enderror
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <label for="dapertement">Jurusan</label>
                <select class="form-control" name="dapertement" id="dapertement">
                    <option value="Teknik Informatika" {{old('dapertement')=='Teknik Informatika' ?'selected':''}}>
                        Teknik Informatika</option>
                    <option value="Sistem Informasi" {{old('dapertement')=='Sistem Informasi' ?'selected':''}}>Sistem
                        Informasi</option>
                    <option value="Ilmu Komputer" {{old('dapertement')=='Ilmu Komputer' ?'selected':''}}>Ilmu Komputer
                    </option>
                    <option value="Teknik Komputer" {{old('dapertement')=='Teknik Komputer' ?'selected':''}}>Teknik
                        Komputer
                    </option>
                    <option value="Teknik Telekomunikasi" {{old('dapertement')=='Teknik Telekomunikasi'
                        ?'selected':''}}>
                        Teknik Telekomunikasi</option>
                </select>
                @error('jurusan')
                <div class="text-danger">
                    {{$message}}
                </div>
                @enderror
            </div>
        </div>
        <div class="form-group">
            <label for="address">Alamat</label>
            <textarea class="form-control" id="address" rows="3" name="address">{{old('alamat')}}</textarea>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center mt-3">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
</form>
@endsection

practice_laravel/resources/views/students/edit.blade.php
@extends('students.layout')

@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div>
            <h2>Edit student</h2>
        </div>
        <div>
            <a class="btn btn-primary" href="{{ route('students.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

<form action="{{ route('students.update',$student->id) }}" method="POST">
    @csrf
    @method('PUT')

    <div class="row">
        <div class="form-group">
            <label for="nim">NIM</label>
            <input type="text" class="form-control @error('nim') is-invalid @enderror" id="nim" name="nim"
                value="{{ $student->nim }}">
            @error('nim')
            <div class="text-danger">
                {{$message}}
            </div>
            @enderror
        </div>
        <div class="form-group">
            <label for="name">NamaLengkap</label>
            <input type="text" class="form-control @error('name')is-invalid @enderror" id="name" name="name"
                value="{{ $student->name }}">
            @error('nama')
            <div class="text-danger">
                {{$message}}
            </div>
            @enderror
        </div>
        <div class="form-group"><label>Jenis Kelamin</label>
            <div>
                <div class="form-checkform-check-inline">
                    <input class="form-check-input" type="radio" name="gender" id="laki_laki" value="L"
                        {{old('gender')==$student->gender ?'checked':''}}>
                    <label class="form-check-label" for="laki_laki">Laki-laki</label>
                </div>
                <div class="form-checkform-check-inline">
                    <input class="form-check-input" type="radio" name="gender" id="perempuan" value="P"
                        {{old('gender')==$student->gender ?'checked':''}}>
                    <label class="form-check-label" for="perempuan">Perempuan</label>
                </div>
                @error('gender')
                <div class="text-danger">
                    {{$message}}
                </div>@enderror
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <label for="dapertement">Jurusan</label>
                <select class="form-control" name="dapertement" id="dapertement">
                    <option value="Teknik Informatika" {{old('dapertement')=='$student->gender' ?'selected':''}}>
                        Teknik Informatika</option>
                    <option value="Sistem Informasi" {{old('dapertement')=='Sistem Informasi' ?'selected':''}}>Sistem
                        Informasi</option>
                    <option value="Ilmu Komputer" {{old('dapertement')=='Ilmu Komputer' ?'selected':''}}>Ilmu Komputer
                    </option>
                    <option value="Teknik Komputer" {{old('dapertement')=='Teknik Komputer' ?'selected':''}}>Teknik
                        Komputer
                    </option>
                    <option value="Teknik Telekomunikasi" {{old('dapertement')=='Teknik Telekomunikasi'
                        ?'selected':''}}>
                        Teknik Telekomunikasi</option>
                </select>
                @error('jurusan')
                <div class="text-danger">
                    {{$message}}
                </div>
                @enderror
            </div>
        </div>
        <div class="form-group">
            <label for="address">Alamat</label>
            <textarea class="form-control" id="address" rows="3" name="address">{{ $student->address }}</textarea>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center mt-3">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>

</form>
@endsection

practice_laravel/resources/views/students/index.blade.php
@extends('students.layout')

@section('content')
<div class="row mt-5">
    <div class="col-lg-12 margin-tb">
        <div class="float-start">
            <h2>Laravel 9 CRUD </h2>
        </div>
        <div class="float-end">
            <a class="btn btn-success" href="{{ route('students.create') }}"> Create New student</a>
        </div>
    </div>
</div>

@if ($message = Session::get('success'))
<div class="alert alert-success">
    <p>{{ $message }}</p>
</div>
@endif

<table class="table table-bordered">
    <tr>
        <th>No</th>
        <th>Nim</th>
        <th>Name</th>
        <th>JenisKelamin</th>
        <th>Jurusan</th>
        <th>Alamat</th>
        <th width="280px">Action</th>
    </tr>
    @foreach ($students as $student)
    <tr>
        <td>{{ ++$i }}</td>
        <td>{{ $student->nim }}</td>
        <td>{{ $student->name }}</td>
        <td>{{ $student->gender }}</td>
        <td>{{ $student->dapertement }}</td>
        <td>{{ $student->address }}</td>
        <td>
            <form action="{{ route('students.destroy',$student->id) }}" method="POST">

                <a class="btn btn-info" href="{{ route('students.show',$student->id) }}">Show</a>

                <a class="btn btn-primary" href="{{ route('students.edit',$student->id) }}">Edit</a>

                @csrf
                @method('DELETE')

                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
        </td>
    </tr>
    @endforeach
</table>
<div class="row text-center">
    {!! $students->links() !!}
</div>

@endsection

practice_laravel/resources/views/students/layout.blade.php
<!DOCTYPE html>
<html>

<head>
    <title>Laravel 9 CRUD School Application</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body>

    <div class="container">
        @yield('content')
    </div>

</body>

</html>

practice_laravel/resources/views/students/show.blade.php
@extends('students.layout')

@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div>
            <h2> Show student</h2>
        </div>
        <div>
            <a class="btn btn-primary" href="{{ route('students.index') }}"> Back</a>
        </div>
    </div>
</div>

<div class="container mt-3">
    <div class="row">
        <div class="col-12">
            <div class="pt-3 d-flex justify-content-end align-items-center">
                <h1 class="h2 mr-auto">Biodata {{$student->name}}</h1>
                <a href="" class="btn btn-primary">Edit</a>
                <form action="" method="POST">
                    @method('DELETE')
                    @csrf
                    <button type="submit" class="btn btn-danger ml-3">Hapus</button>
                </form>
            </div>
            <hr>
            @if(session()->has('pesan'))
            <div class="alert alert-success">
                {{session()->get('pesan')}}
            </div>
            @endif
            <ul>
                <li>NIM:{{$student->nim}}</li>
                <li>Nama:{{$student->name}}</li>
                <li>Jenis Kelamin:{{$student->gender == 'P'?'Perempuan':'Laki-laki'}}</li>
                <li>Jurusan:{{$student->dapertement}}</li>
                <li>Alamat:{{$student->address==''?'N/A':$student->address}}</li>
            </ul>
        </div>
    </div>
</div>
@endsection